/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PharmcistRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Enterprises.RescueCenterEntDetails;
import model.Medicines.MedicineDetails;
import model.Organisation.PharmacyOrganisation;
import model.WorkQueue.AllWorkRequest;
import model.WorkQueue.PharmacyUnitWre;
import model.WorkQueue.PharmacyWre;

/**
 *
 * @author manohar
 */
public class MedicineAnalyseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAnalyseJPanel
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private PharmacyOrganisation organization;
    
    public MedicineAnalyseJPanel(JPanel container, RescueCenterEntDetails enterprise,PharmacyOrganisation organization) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = organization;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
        model.setRowCount(0);
        for(MedicineDetails m: enterprise.getMedicineDirectory()) {
            int count = 0;
            Object[] row = new Object[2];
            row[0] = m;
            for(AllWorkRequest wr: organization.getWorkQueue()) {
                if(wr instanceof PharmacyWre pharmacyWre) {
                    if(pharmacyWre.getMedicineList() != null) {
                        for(PharmacyUnitWre ru: pharmacyWre.getMedicineList()) {
                            if(ru.getMedicine().getId() == m.getId()) {
                                count += ru.getQuantity();
                            }
                        }
                    }
                }
            }
            row[1] = count;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblmedicineanalysis = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setForeground(new java.awt.Color(255, 51, 51));
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, 81, 32));

        lblmedicineanalysis.setBackground(new java.awt.Color(255, 255, 255));
        lblmedicineanalysis.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblmedicineanalysis.setForeground(new java.awt.Color(51, 0, 51));
        lblmedicineanalysis.setText("MEDICINE ANALYSIS");
        add(lblmedicineanalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Amount Used"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicine.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tblMedicine);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 550, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -10, 1930, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmedicineanalysis;
    private javax.swing.JTable tblMedicine;
    // End of variables declaration//GEN-END:variables
}
