/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.SysAdminRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sejal
 */
public class AnalysisJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalysisJPanel
     */
    
    private JPanel userProcessContainer;
    
    public AnalysisJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton1 = new javax.swing.JButton();
        lblanalysisfig = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAnimals = new javax.swing.JButton();
        btnAdoptions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton1.setBackground(new java.awt.Color(204, 204, 255));
        backJButton1.setText("Previous");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 81, -1));

        lblanalysisfig.setBackground(new java.awt.Color(255, 255, 255));
        lblanalysisfig.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblanalysisfig.setForeground(new java.awt.Color(204, 204, 255));
        lblanalysisfig.setText("ANALYSIS FIGURES");
        add(lblanalysisfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAnimals.setBackground(new java.awt.Color(204, 204, 255));
        btnAnimals.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAnimals.setText("ANIMALS");
        btnAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalsActionPerformed(evt);
            }
        });

        btnAdoptions.setBackground(new java.awt.Color(204, 204, 255));
        btnAdoptions.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAdoptions.setText(" ADOPTIONS");
        btnAdoptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAdoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Analysis.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1930, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalsActionPerformed
        // TODO add your handling code here:
        AnalyseAnimalsJPanel analyseAnimalsJPanel = new AnalyseAnimalsJPanel(userProcessContainer);
        userProcessContainer.add("analyseAnimalsJPanel",analyseAnimalsJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnimalsActionPerformed

    private void btnAdoptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptionsActionPerformed
        // TODO add your handling code here:
        AnalyseAdoptionsJPanel analyseAdoptionsJPanel=new AnalyseAdoptionsJPanel(userProcessContainer);
        userProcessContainer.add("analyseAdoptionsJPanel",analyseAdoptionsJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdoptionsActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton btnAdoptions;
    private javax.swing.JButton btnAnimals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblanalysisfig;
    // End of variables declaration//GEN-END:variables
}
