/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptorRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AdoptDetails.AdopterDetails;

/**
 *
 * @author manohar
 */
public class AdoptorPage extends javax.swing.JPanel {

    /**
     * Creates new form AdoptorPage
     */
    private JPanel container;
    private AdopterDetails adoptor;
    
    public AdoptorPage(JPanel container, AdopterDetails adoptor) {
        initComponents();
        this.container  = container;
        this.adoptor = adoptor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnimal = new javax.swing.JLabel();
        btnMyAdoptionlist = new javax.swing.JButton();
        btnAdoptList = new javax.swing.JButton();
        btnEditInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnimal.setBackground(new java.awt.Color(255, 255, 255));
        lblAnimal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAnimal.setText("ANIMAL RESCUE CENTER");
        add(lblAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        btnMyAdoptionlist.setText("My Adoption List");
        btnMyAdoptionlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAdoptionlistActionPerformed(evt);
            }
        });
        add(btnMyAdoptionlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 214, 43));

        btnAdoptList.setText("Adoption Details");
        btnAdoptList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptListActionPerformed(evt);
            }
        });
        add(btnAdoptList, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 214, 43));

        btnEditInfo.setText("Edit Details");
        btnEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoActionPerformed(evt);
            }
        });
        add(btnEditInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 680, 214, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91833\\Downloads\\All Animals.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -40, 1930, 1130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyAdoptionlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAdoptionlistActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("MyAdoptionsJPanel", new MyAdoptPage(container, adoptor));
        layout.next(container);
    }//GEN-LAST:event_btnMyAdoptionlistActionPerformed

    private void btnAdoptListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptListActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("AdoptorListJPanel", new AdoptlistPage(container, adoptor));
        layout.next(container);
    }//GEN-LAST:event_btnAdoptListActionPerformed

    private void btnEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("AdoptorInformationJPanel", new AdoptInfoPage(container, adoptor));
        layout.next(container);
    }//GEN-LAST:event_btnEditInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdoptList;
    private javax.swing.JButton btnEditInfo;
    private javax.swing.JButton btnMyAdoptionlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnimal;
    // End of variables declaration//GEN-END:variables
}
