/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptorRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.AdoptDetails.AdopterDetails;
import model.AdoptDetails.AdoptionOffered;
import model.Enterprises.EnterpriseDetails;
import model.Enterprises.RescueCenterEntDetails;
import model.Network.NetworkDetails;

/**
 *
 * @author manohar
 */
public class AdoptlistPage extends javax.swing.JPanel {

    /**
     * Creates new form AdoptlistPage
     */
    
    private JPanel container;
    private AdopterDetails adoptor;
    
    public AdoptlistPage(JPanel container, AdopterDetails adoptor) {
        initComponents();
        this.container = container;
        this.adoptor = adoptor;
        
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblOffering.getModel();
        model.setRowCount(0);
        
        for(NetworkDetails n: new NetworkDetails().getNetworkList()) {
            for(EnterpriseDetails e: n.getEnterpriseDirectory()) {
                if(e instanceof RescueCenterEntDetails) {
                    for(AdoptionOffered ao: ((RescueCenterEntDetails) e).getAdoptionList()) {
                        if(ao.getStatus() != null) {
                            if(ao.getStatus().equals(AdoptionOffered.Status.Open)) {
                                Object[] row = new Object[5];
                                row[0] = ao;
                                row[1] = ao.getAnimal().getColor();
                                row[2] = ao.getAnimal().getAge();

                                int size = ao.getAnimal().getStatusDirectory().size();
                                row[3] = ao.getAnimal().getStatusDirectory().get(size-1).getWeight();

                                row[4] = ao.getPublishDate().toString();
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdoptionlist = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOffering = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdoptionlist.setBackground(new java.awt.Color(255, 255, 255));
        lblAdoptionlist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdoptionlist.setForeground(new java.awt.Color(255, 51, 51));
        lblAdoptionlist.setText("ADOPTION DETAILS");
        add(lblAdoptionlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        btnDetails.setForeground(new java.awt.Color(255, 0, 0));
        btnDetails.setText("Check Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 750, -1, 31));

        btnPrevious.setForeground(new java.awt.Color(255, 51, 51));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 750, 102, 32));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        tblOffering.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal Type", "Color", "Age", "Weight", "Published Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOffering.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tblOffering);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpgtopngconverter-com (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1930, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOffering.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        AdoptionOffered ao = (AdoptionOffered)tblOffering.getValueAt(selectedRow, 0);
        
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("SeeOfferingDetailJPanel", new SeeOfferinginfoPage(container, adoptor, ao));
        layout.next(container);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdoptionlist;
    private javax.swing.JTable tblOffering;
    // End of variables declaration//GEN-END:variables
}
