/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptorRole;

import model.AdoptDetails.AdoptHistory;
import model.AdoptDetails.AdopterDetails;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manohar
 */
public class MyAdoptPage extends javax.swing.JPanel {

    private JPanel container;
    private AdopterDetails adoptor;
    
    MyAdoptPage(JPanel container, AdopterDetails adoptor) {
        initComponents();
        this.container = container;
        this.adoptor = adoptor;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblHistory.getModel();
        model.setRowCount(0);
        for(AdoptHistory ah: adoptor.getHistory()) {
            Object[] row = new Object[4];
            row[0] = ah;
            row[1] = ah.getDetails().getType().toString();
            row[2] = ah.getDetails().getColor();
            row[3] = ah.getStatus();
            
            model.addRow(row);
        }
    }

    /**
     * Creates new form MyAdoptionsJPanel
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JButton();
        lblAdoptions = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setForeground(new java.awt.Color(255, 51, 51));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 730, -1, -1));

        lblAdoptions.setBackground(new java.awt.Color(255, 255, 255));
        lblAdoptions.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdoptions.setForeground(new java.awt.Color(255, 51, 51));
        lblAdoptions.setText("MY ADOPTION DETAILS");
        add(lblAdoptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        btnDetails.setForeground(new java.awt.Color(255, 51, 51));
        btnDetails.setText("See Detail");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 730, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adoption Date(MM/DD/YYYY)", "Animal Type", "Color", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistory.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tblHistory);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 302, 820, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91833\\Downloads\\jpgtopngconverter-com (2).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1930, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHistory.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        AdoptHistory ah = (AdoptHistory)tblHistory.getValueAt(selectedRow, 0);

        CardLayout layout = (CardLayout) container.getLayout();
        container.add("SeeHistoryDetailJPanel", new SeeHistoryPage(container, ah));
        layout.next(container);
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdoptions;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables
}
