/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptorRole;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.AdoptDetails.AdoptHistory;
import model.Deliver.DeliveryDetails;
import model.Enterprises.EnterpriseDetails;
import model.Enterprises.RescueCenterEntDetails;
import model.Network.NetworkDetails;

/**
 *
 * @author manohar
 */
public class SeeDeliverydetailspage extends javax.swing.JPanel {

    /**
     * Creates new form SeeDeliverydetailspage
     */
    
    private JPanel container;
    private AdoptHistory history;
    private DeliveryDetails dh;
    
    SeeDeliverydetailspage(JPanel container, AdoptHistory history) {
        initComponents();
        this.container = container;
        this.history = history;
        for(NetworkDetails n: new NetworkDetails().getNetworkList()) {
            for(EnterpriseDetails e: n.getEnterpriseDirectory()) {
                if(e instanceof RescueCenterEntDetails rescueCenterEntDetails) {
                    for(DeliveryDetails a: rescueCenterEntDetails.getDeliveryHistoryDirectory(    )) {
                        if(a.getAnimal() == history.getDetails()) {
                            this.dh = a;
                        } 
                    }
                }
            }
        }
        btnRcv.setVisible(false);
        if(dh.getStatus().equals(DeliveryDetails.Status.ASSIGNED)) {
            btnRcv.setVisible(true);
        }
        
        populateValues();
    }

    public void populateValues() {
        if(dh.getDate() == null) {
            lblDate.setText("Waiting...");
        }
        else {
            String dateFormat = dh.getDate().getMonth()
                                + "/" + dh.getDate().getDate()
                                + "/" + dh.getDate().getYear();
            lblDate.setText(dateFormat);
        }
        
        if(dh.getCourierdetail() == null) {
            lblId.setText("Not Assigned");
        }
        else {
            lblId.setText(String.valueOf(dh.getCourierdetail().getId()));
        }
        
        if(dh.getStatus().equals(DeliveryDetails.Status.WAITING)) {
            lblStatus.setText("Waiting...");
        }
        else if(dh.getStatus().equals(DeliveryDetails.Status.ASSIGNED)) {
            lblStatus.setText("In Progress");
        }
        else if(dh.getStatus().equals(DeliveryDetails.Status.RECEIVED)) {
            lblStatus.setText("Arrived");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JButton();
        lblDeliveryInfo = new javax.swing.JLabel();
        btnRcv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDeliveryDt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setForeground(new java.awt.Color(255, 51, 51));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 81, 32));

        lblDeliveryInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblDeliveryInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDeliveryInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblDeliveryInfo.setText("Delivery Information");
        add(lblDeliveryInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btnRcv.setForeground(new java.awt.Color(255, 51, 0));
        btnRcv.setText("Receive");
        btnRcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRcvActionPerformed(evt);
            }
        });
        add(btnRcv, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 86, 34));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStatus.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblStatus.setText("<value>");

        lblStats.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblStats.setText("Status:");

        lblEmployee.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblEmployee.setText("Employee ID:");

        lblId.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblId.setText("<value>");

        lblDate.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblDate.setText("<value>");

        lblDeliveryDt.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblDeliveryDt.setText("Delivery Date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDeliveryDt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(lblStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryDt)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStats)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployee)
                    .addComponent(lblId))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 410, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91833\\Downloads\\jpgtopngconverter-com (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1930, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SeeHistoryPage shdjp = (SeeHistoryPage) component;
        shdjp.populateValues();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnRcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRcvActionPerformed
        // TODO add your handling code here:
        dh.setStatus(DeliveryDetails.Status.RECEIVED);
        JOptionPane.showMessageDialog(null, "Thank you for your feedback!");
        btnRcv.setVisible(false);
    }//GEN-LAST:event_btnRcvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRcv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDeliveryDt;
    private javax.swing.JLabel lblDeliveryInfo;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
