/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.VetAssistRole;

import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Animal.AnimalDetails;
import model.Cages.CageDetail;
import model.Enterprises.EnterpriseDetails;
import model.Enterprises.RescueCenterEntDetails;
import model.Organisation.CageOrganisation;
import model.Organisation.VeterinarianOrganisation;
import model.Treatment.TreatmentRecord;
import model.UserAccount.UserAccount;

/**
 *
 * @author manohar
 */
public class VeteAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VeteAssistantWorkAreaJPanel
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private CageOrganisation organization;
    private UserAccount userAccount;
    
    public VeteAssistantWorkAreaJPanel(JPanel container, EnterpriseDetails enterprise, CageOrganisation cageOrg, UserAccount userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = cageOrg;
        this.userAccount = userAccount;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblCage.getModel();
        model.setRowCount(0);
        
        for(CageDetail c: enterprise.getCageCellDirectory()){
            if(c.getCagestatus() == CageDetail.Status.OCCUPIED 
                    && c.getAnimal().getStatus() == AnimalDetails.Status.NOT_READY) {
                List<TreatmentRecord> t = c.getAnimal().getTreatmentRecord();
                int size = t.size();
                if(t.get(size-1).isIsReviewed() == true) {
                    break;
                }
                
                Object[] row = new Object[5];
                row[0] = c;
                row[1] = c.getCagelocation();
                row[2] = c.getAnimal().getType();
                row[3] = c.getAnimal().getColor();
                row[4] = c.getAnimal().getNextCheck().toString();
                model.addRow(row);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblveterassistant = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCage = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblveterassistant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblveterassistant.setText("VETERINARIAN ASSISTANT");
        add(lblveterassistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        btnAssign.setText("Self Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, 31));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblCage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cage", "Location", "Animal Type", "Color", "Review Date(MM/DD/YYYY)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinary.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 1930, 1200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCage.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        CageDetail c = (CageDetail)tblCage.getValueAt(selectedRow, 0);
        
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ReviewAnimalJPanel", new ReviewAnimalJPanel(container, enterprise, c));
        layout.next(container);
        
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblveterassistant;
    private javax.swing.JTable tblCage;
    // End of variables declaration//GEN-END:variables
}
