/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptInspectRole;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.AdoptDetails.AdoptRecord;
import model.Enterprises.EnterpriseDetails;
import model.Enterprises.RescueCenterEntDetails;
import model.Organisation.AdoptionOrganisation;
import model.UserAccount.UserAccount;

/**
 *
 * @author sejal
 */
public class AdoptInspectorWorkpage extends javax.swing.JPanel {

    /**
     * Creates new form AdoptInspectorWorkpage
     */
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private AdoptionOrganisation organization;
    private UserAccount userAccount;
    
    public AdoptInspectorWorkpage(JPanel container, EnterpriseDetails enterprise, AdoptionOrganisation adoptionOrg, UserAccount userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = adoptionOrg;
        this.userAccount = userAccount;
        
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblApplication.getModel();
        model.setRowCount(0);
        
        for(AdoptRecord ar: organization.getAdoptionRecordDirectory()) {
            if(ar.getStatus() == AdoptRecord.Status.Submitted) {
                Object[] row = new Object[5];
                row[0] = ar;
                row[1] = ar.getAnimal().getId();
                row[2] = ar.getAdoptor().getFirstName() + " " + ar.getAdoptor().getLastName();
                row[3] = ar.getAdoptor().getPhoneNumber();
                row[4] = ar.getAdoptor().getEmail();
                model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdoption = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplication = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnMy = new javax.swing.JButton();
        btnAnalyse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdoption.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblAdoption.setForeground(new java.awt.Color(255, 51, 51));
        lblAdoption.setText("ADOPTION INSPECTOR PANEL");
        add(lblAdoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 370, 40));

        tblApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submitted Date", "Animal ID", "Name", "Phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblApplication.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tblApplication);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 630, 190));

        btnAssign.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(255, 0, 0));
        btnAssign.setText("Assign to Self");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 139, 30));

        btnMy.setForeground(new java.awt.Color(255, 51, 51));
        btnMy.setText("Inspect");
        btnMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyActionPerformed(evt);
            }
        });
        add(btnMy, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 30));

        btnAnalyse.setForeground(new java.awt.Color(255, 51, 51));
        btnAnalyse.setText("Analyze");
        btnAnalyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyseActionPerformed(evt);
            }
        });
        add(btnAnalyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 95, 30));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 630, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_2.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1650, 1040));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblApplication.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        AdoptRecord ar = (AdoptRecord)tblApplication.getValueAt(selectedRow, 0);
        UserAccount ua = userAccount;
        ar.setEmployee(ua.getEmployee());
        ar.setStatus(AdoptRecord.Status.Processing);
        
        populateTable();
        JOptionPane.showMessageDialog(null, "Work has been assigned to you. Please view it in My Inspections panel.");
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("MyInspectionJPanel", new MyInspectPanel(container, enterprise, organization, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnMyActionPerformed

    private void btnAnalyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyseActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("AdoptionOrgAnalyseJPanel", new AdoptOrganalyze(container, enterprise, organization, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnAnalyseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyse;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnMy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdoption;
    private javax.swing.JTable tblApplication;
    // End of variables declaration//GEN-END:variables
}
