/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.AdoptInspectRole;

import controller.Helper.Helper;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.AdoptDetails.AdoptHistory;
import model.AdoptDetails.AdoptRecord;
import model.AdoptDetails.AdopterDetails;
import model.AdoptDetails.AdoptionOffered;
import model.Animal.AnimalDetails;
import model.Deliver.DeliveryDetails;
import model.Enterprises.RescueCenterEntDetails;
import view.Main.Main;

/**
 *
 * @author sejal
 */
public class EvaluationPage extends javax.swing.JPanel {

    /**
     * Creates new form EvaluationPage
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private AdoptRecord ar;
    Helper validations;
    
    EvaluationPage(JPanel container, RescueCenterEntDetails enterprise, AdoptRecord ar) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.ar = ar;
        this.validations = new Helper();
        rbtnApprove.setSelected(true);
        txtMessage.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResult = new javax.swing.ButtonGroup();
        btnPrevious = new javax.swing.JButton();
        lblEvaluateApp = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        rbtnApprove = new javax.swing.JRadioButton();
        rbtnReject = new javax.swing.JRadioButton();
        lblDeliveryDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        lblReason = new javax.swing.JLabel();
        txtDate = new com.github.lgooddatepicker.components.DatePicker();
        valDate = new javax.swing.JLabel();
        valResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, 30));

        lblEvaluateApp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEvaluateApp.setForeground(new java.awt.Color(51, 0, 51));
        lblEvaluateApp.setText("APPLICANT EVALUATION");
        add(lblEvaluateApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblResult.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblResult.setText("Result:");

        rbtnApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnResult.add(rbtnApprove);
        rbtnApprove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtnApprove.setText("Approve");

        rbtnReject.setBackground(new java.awt.Color(255, 255, 255));
        btnResult.add(rbtnReject);
        rbtnReject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtnReject.setText("Reject");

        lblDeliveryDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDeliveryDate.setText("Delivery Date:");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        txtMessage.setEnabled(false);
        txtMessage.setSelectionColor(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(txtMessage);

        lblReason.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblReason.setText("Reason:");

        valDate.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        valDate.setForeground(new java.awt.Color(255, 0, 0));

        valResult.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        valResult.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReason)
                    .addComponent(lblDeliveryDate)
                    .addComponent(lblResult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valDate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valResult, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblResult)
                        .addComponent(rbtnApprove)
                        .addComponent(rbtnReject))
                    .addComponent(valResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeliveryDate)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReason)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 620, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OBl3g7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CheckInspectInfo sidjp = (CheckInspectInfo) component;
        sidjp.populateButton();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        var valid = true;
        if (!this.validations.ValidateEmpty(txtDate.getDateStringOrEmptyString()) ) {
            valDate.setText("Date is required");
            valid = false;
        }
        
        if (btnResult.getSelection() == null) {
            valResult.setText("Gender is required");
            valid = false;
        }

        
        if(rbtnReject.isSelected()) {
            if(!this.validations.ValidateEmpty(txtMessage.getText())) {
                JOptionPane.showMessageDialog(null, "Please fill out the reason for rejection.");
                return;
            }
        }
        if (valid) {
        if(rbtnApprove.isSelected()) {
            ar.setStatus(AdoptRecord.Status.Approved);
            int size = ar.getAdoptor().getHistory().size();
            ar.getAdoptor().getHistory().get(size-1).setStatus(AdoptHistory.Status.Approved);
            ar.getAnimal().setStatus(AnimalDetails.Status.ADOPTED);
            Main.controller.saveOrUpdate(ar.getAdoptor().getHistory().get(size-1));
            Main.controller.saveOrUpdate(ar.getAnimal());
            Main.controller.saveOrUpdate(ar);
            
            DeliveryDetails dh = new DeliveryDetails();
            dh.setAdoptername(ar.getAdoptor());
            dh.setAnimal(ar.getAnimal());
            dh.setStatus(DeliveryDetails.Status.WAITING);
            
            Date date = this.validations.getFormattedDate(txtDate);
            dh.setDate(date);
            Main.controller.saveObject(dh);
            enterprise.getDeliveryHistoryDirectory().add(dh);
            Main.controller.saveOrUpdate(enterprise);
        }
        else if(rbtnReject.isSelected()) {
            ar.setStatus(AdoptRecord.Status.Rejected);
            int size = ar.getAdoptor().getHistory().size();
            ar.getAdoptor().getHistory().get(size-1).setMessage(txtMessage.getText());
            ar.getAdoptor().getHistory().get(size-1).setStatus(AdoptHistory.Status.Rejected);
            Main.controller.saveOrUpdate(ar.getAdoptor().getHistory().get(size-1));
            Main.controller.saveOrUpdate(ar.getAnimal());
            Main.controller.saveOrUpdate(ar);
            for(AdoptionOffered ao: enterprise.getAdoptionList()) {
                if(ao.getAnimal().getId() == ar.getAnimal().getId()) {
                    ao.setStatus(AdoptionOffered.Status.Open);
                    Main.controller.saveOrUpdate(ao);
                }
            }
        }
        
        btnSubmit.setVisible(false);
        setTextNull();
        JOptionPane.showMessageDialog(null, "Evaluated Successfully.\nResult has been sent.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void setTextNull() {
        btnResult.clearSelection();
        txtDate.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup btnResult;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeliveryDate;
    private javax.swing.JLabel lblEvaluateApp;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblResult;
    private javax.swing.JRadioButton rbtnApprove;
    private javax.swing.JRadioButton rbtnReject;
    private com.github.lgooddatepicker.components.DatePicker txtDate;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JLabel valDate;
    private javax.swing.JLabel valResult;
    // End of variables declaration//GEN-END:variables
}
