/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ReceptionistRole;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Enterprises.RescueCenterEntDetails;
import model.Organisation.CenterRegistrationOrganisation;
import model.RescueRecord.RescueRecordDetails;
import model.UserAccount.UserAccount;

/**
 *
 * @author manohar
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistWorkAreaJPanel
     */
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private CenterRegistrationOrganisation organization;
    private UserAccount userAccount;
    
    public ReceptionistWorkAreaJPanel(JPanel container, RescueCenterEntDetails enterprise, CenterRegistrationOrganisation organization, UserAccount userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        
        populateAnimalTable();
    }
    
   
    
    public void populateAnimalTable() {
        DefaultTableModel model = (DefaultTableModel) tblAnimal.getModel();

        model.setRowCount(0);
        for (RescueRecordDetails r : enterprise.getRecordDirectory()) {
            Object[] row = new Object[4];
            row[0] = r;
            row[1] = r.getRescuedanimal().getId();
            row[2] = r.getRescuedanimal().getType().toString();
            if(r.getRescueroom() == null) {
                row[3] = "Waiting...";
            }
            else {
                row[3] = r.getRescueroom().getRoomNumber();
            } 
            
            model.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcentrereceptionist = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcentrereceptionist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblcentrereceptionist.setText("CENTRE RECEPTIONIST WORKPLACE");
        add(lblcentrereceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        btnRegister.setText("Register New");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, -1, 37));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Animal ID", "Animal Type", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnimal);
        if (tblAnimal.getColumnModel().getColumnCount() > 0) {
            tblAnimal.getColumnModel().getColumn(0).setResizable(false);
            tblAnimal.getColumnModel().getColumn(1).setResizable(false);
            tblAnimal.getColumnModel().getColumn(2).setResizable(false);
            tblAnimal.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif-2-8b9f655bd0.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -10, 1930, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("RequestLabTestJPanel", new RegisterAnimalJPanel(container, enterprise, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcentrereceptionist;
    private javax.swing.JTable tblAnimal;
    // End of variables declaration//GEN-END:variables
}
