/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ReceptionistRole;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Animal.AnimalDetails;
import model.Animal.CatDetails;
import model.Animal.DogDetails;
import model.Animal.OtherAnimalDetails;
import model.Enterprises.RescueCenterEntDetails;
import model.RescueRecord.RescueRecordDetails;
import model.UserAccount.UserAccount;
import view.Main.Main;

/**
 *
 * @author manohar
 */
public class RegisterAnimalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterAnimalJPanel
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private UserAccount userAccount;
    
    public RegisterAnimalJPanel(JPanel container, RescueCenterEntDetails enterprise, UserAccount userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        rbtnM.setSelected(true);
        populateComboBox();
    }

    public void populateComboBox() {
        cboxType.removeAllItems();
        for (AnimalDetails.AnimalType type : AnimalDetails.AnimalType.values()) {
            cboxType.addItem(type);
        }
    }
    
    public void clearFields() {
        cboxType.setSelectedIndex(0);
        txtType.setEnabled(false);
        txtType.setText("");
        txtColor.setText("");
        rbtnM.setSelected(true);
        rbtnF.setSelected(false);
        txtLocationFound.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblregisteranimal = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboxType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtLocationFound = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnF = new javax.swing.JRadioButton();
        rbtnM = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblregisteranimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblregisteranimal.setText("REGISTER NEW ANIMAL");
        add(lblregisteranimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, 32));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 81, 32));

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 81, 32));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("Animal Type:");

        cboxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("Type:");

        txtType.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("Color:");

        rbtnF.setText("F");
        rbtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFActionPerformed(evt);
            }
        });

        rbtnM.setText("M");
        rbtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("Location Found:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtColor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnM)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnF))
                    .addComponent(txtLocationFound)
                    .addComponent(txtType)
                    .addComponent(cboxType, 0, 114, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnM)
                    .addComponent(rbtnF))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLocationFound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All Animals.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1930, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if(txtColor.getText().equals("") || txtLocationFound.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
            return;
        }
        else if(cboxType.getSelectedItem() == AnimalDetails.AnimalType.Other
                && txtType.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Type is required!");
            return;
        }
        RescueRecordDetails r = new RescueRecordDetails();
        AnimalDetails a;
        if(cboxType.getSelectedItem() == AnimalDetails.AnimalType.Cat) {
            a = new CatDetails();
            a.setColor(txtColor.getText());
            a.setType(AnimalDetails.AnimalType.Cat);
            
        }
        else if(cboxType.getSelectedItem() == AnimalDetails.AnimalType.Dog) {
            a = new DogDetails();
            a.setColor(txtColor.getText());
            a.setType(AnimalDetails.AnimalType.Dog);
        }
        else {
            a = new OtherAnimalDetails();
            a.setColor(txtColor.getText());
            a.setType(AnimalDetails.AnimalType.Other);
        }
        a.setStatus(AnimalDetails.Status.NOT_READY);
        Main.controller.saveObject(a);
        enterprise.getAnimalDirectory().add(a);
        
        r.setRescuedanimal(a);
        
        Date d = new Date();
        
        if(rbtnM.isSelected() == true) {
            r.getRescuedanimal().setGender("M");
        }
        else {
            r.getRescuedanimal().setGender("F");
        }
        
        
        
        r.setDate(d);
        r.setFoundlocation(txtLocationFound.getText());
        Main.controller.saveObject(r);
        Main.controller.saveOrUpdate(r.getRescuedanimal());
        enterprise.getRecordDirectory().add(r);
        Main.controller.saveOrUpdate(enterprise);
        JOptionPane.showMessageDialog(null, "Registered Successfully!");
        clearFields();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ReceptionistWorkAreaJPanel crwjp = (ReceptionistWorkAreaJPanel) component;
        crwjp.populateAnimalTable();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cboxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTypeActionPerformed
        // TODO add your handling code here:
        if(cboxType.getSelectedItem() == AnimalDetails.AnimalType.Other) {
            txtType.setEnabled(true);
        }
        else {
            txtType.setEnabled(false);
        }
    }//GEN-LAST:event_cboxTypeActionPerformed

    private void rbtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMActionPerformed
        // TODO add your handling code here:
        rbtnF.setSelected(false);
    }//GEN-LAST:event_rbtnMActionPerformed

    private void rbtnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFActionPerformed
        // TODO add your handling code here:
        rbtnM.setSelected(false);
    }//GEN-LAST:event_rbtnFActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox cboxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblregisteranimal;
    private javax.swing.JRadioButton rbtnF;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLocationFound;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
