/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.EntAdminRole;

import model.Enterprises.EnterpriseDetails;

import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author manohar
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EnterpriseDetails enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EnterpriseDetails enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        lblValue.setText(enterprise.getName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelentworkarea = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        btnManageEmployee = new javax.swing.JButton();
        btnManageOrganization = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRoom = new javax.swing.JButton();
        btnMedicine = new javax.swing.JButton();
        btnCage = new javax.swing.JButton();
        btnShelter = new javax.swing.JButton();
        btnAnalyse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelentworkarea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelentworkarea.setText("Enterprise Admin Work Area");
        add(jLabelentworkarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        btnUser.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnUser.setText("Manage User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 171, 50));

        btnManageEmployee.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });
        add(btnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 171, 50));

        btnManageOrganization.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });
        add(btnManageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 310, -1, 50));

        enterpriseLabel.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 105, 20));

        lblValue.setBackground(new java.awt.Color(255, 255, 255));
        lblValue.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 145, 20));

        btnRoom.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnRoom.setText("Manage Room");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 171, 50));

        btnMedicine.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnMedicine.setText("Manage Medicine");
        btnMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineActionPerformed(evt);
            }
        });
        add(btnMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 171, 50));

        btnCage.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCage.setText("Manage Cage");
        btnCage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCageActionPerformed(evt);
            }
        });
        add(btnCage, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 171, 50));

        btnShelter.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnShelter.setText("Manage Shelter");
        btnShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShelterActionPerformed(evt);
            }
        });
        add(btnShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 171, 50));

        btnAnalyse.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnAnalyse.setText("Analysis");
        btnAnalyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyseActionPerformed(evt);
            }
        });
        add(btnAnalyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 171, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif-2-8b9f655bd0.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1930, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
        ManageRoomsJPanel manageRoomsJPanel = new ManageRoomsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageRoomsJPanel", manageRoomsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineActionPerformed
        // TODO add your handling code here:
        ManageMedicineJPanel manageMedicineJPanel = new ManageMedicineJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageMedicineJPanel", manageMedicineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMedicineActionPerformed

    private void btnCageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCageActionPerformed
        // TODO add your handling code here:
        ManageCageJPanel manageCageJPanel = new ManageCageJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageCageJPanel", manageCageJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCageActionPerformed

    private void btnShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShelterActionPerformed
        // TODO add your handling code here:
        ManageShelterJPanel manageShelterJPanel = new ManageShelterJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageShelterJPanel", manageShelterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnShelterActionPerformed

    private void btnAnalyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyseActionPerformed
        // TODO add your handling code here:
        EnterpriseAnalyseJPanel enterpriseAnalyseJPanel = new EnterpriseAnalyseJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("enterpriseAnalyseJPanel", enterpriseAnalyseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalyseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyse;
    private javax.swing.JButton btnCage;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnMedicine;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnShelter;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelentworkarea;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
